# 前缀名称
prefix_name: &eShining

# SQL数据库
database:
  # enable 为 false 时使用 SQLite 存储数据
  # 若要使用自定义的数据库请将 enable 改为 true
  enable: false
  host: localhost
  port: 3306
  user: root
  password: root
  database: root
  # 玩家数据库表名
  player_table: player

# 自动保存时间间隔[单位: tick] (默认为6000tick,即5分钟)
auto_save_period: 6000